server:
  error:
    whitelabel:
      enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: deleted
            clientSecret : deleted
            redirectUri: http://localhost:8080/login/oauth2/code/github
